apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: shivaraj3652/user-management-apiservice:v1
          env:
            - name: APIPORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: APIPORT
            - name: GRPCUSERPORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: GRPCUSERPORT
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30080
  type: NodePort